name: Deploy to Database

on:
  push:
    branches:
      - main  # Триггер на пуш в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Проверяет репозиторий

      - name: Run a multi-line script
        run: |
          echo "Running database migration script..."
          # Путь к файлу в репозитории
          psql -h $DB_HOST -U $DB_USER -d $DB_NAME -f manuscript_pg/01_create_table/test.sql
