name: Deploy to Database

on:
  push:
    branches:
      - main  # Триггер на пуш в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu для работы

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run a multi-line script
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        echo "Running database migration script..."
        # Путь к файлу в репозитории
        PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d $DB_NAME -f manuscript_pg/01_create_table/test.sql
