name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Setup minio
        run: |
          docker run  -d --name minio -p 9000:9000 
                     -e "MINIO_ACCESS_KEY=minioadmin" 
                     -e "MINIO_SECRET_KEY=minioadmin" 
                     -v /tmp/data:/data 
                     -v /tmp/config:/root/.minio 
                     minio/minio server /data
          export AWS_ACCESS_KEY_ID=minioadmin
          export AWS_SECRET_ACCESS_KEY=minioadmin
          export AWS_EC2_METADATA_DISABLED=true
          aws --endpoint-url http://127.0.0.1:9000/ s3 mb s3://testbucket
      - name: Run Go Test
        run: go test -v ./...
        env:
          AWS_S3_BUCKET: testbucket
          AWS_S3_ACCESS_KEY: minioadmin
          AWS_S3_SECRET_KEY: minioadmin
          AWS_S3_ENDPOINT: http://127.0.0.1:9000